### ISSUE TITLE
Animated player sprite

### ISSUE THREAD

**Issue by ghost** [templetonm/Troglodytes#1]
Finish up animations on player sprites and make it modular so that we can add/remove the animation component if we want to.

**Comment by parkb** [comment]
I've reworked parts of the character already and just need to forward those to Rob tonight. Dino should be done late tonight as well.

**Comment by ghost** [comment]
I created another issue for that #7

**Comment by sikrob** [comment]
I've got most of the player stuff halfway in place. What I need at this point:
1) Player sprite sheet in the final format.
2) Attack input mappings to be completed so I know how to address the animations there.

**Comment by ghost** [comment]
Looks pretty good. I created a bug issue #15 relating to the collision detection and assigned it to Ben. Feel free to take that over if it's easier for you.
