### ISSUE TITLE
Particle system should use a component mapper

### ISSUE THREAD

**Issue by ghost** [templetonm/Troglodytes#39]
Currently:
entity.getComponent(ParticleComponent.class)

It should be like this:
positionMapper = new ComponentMapper<Position>(Position.class, world);
positionMapper.get(entity);

**Comment by sikrob** [comment]
I'll be fixing this momentarily; I'll also be adding the Renderable component usage for the map particle system stuff. Previously it depended on RenderType, but while that was effectively removed, Renderable was never added to replace it.

**Comment by sikrob** [comment]
Issue solved in branch issue39. Merge with development when convenient.
