### ISSUE TITLE
Reformat sprite sheets for movement and action

### ISSUE THREAD

**Issue by ghost** [templetonm/Troglodytes#7]
Sprites sheets should be consistent with each other (i.e attack animation is always on the same frame). We need this format defined and our current sprite to use this format.

**Comment by parkb** [comment]
Done. (1/23/2012)
Top four rows of every sheet will be movement animations
Bottom four rows will be attacks
Orientation of attacks will follow the same orientation as movement (ie. 1st row is down, 2nd row is left, etc.)

**Comment by sikrob** [comment]
Can you reorder the right movement row? I'd like to make the loading of things really uniform and right now the right movement is 'moonwalking' if loaded in the same order as the other rows.
